/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MenuItemType } from "./components/bc-menu/bc-menu";
import { AutoPlayType, PerloadType } from "./components/bc-video/bc-video";
export { MenuItemType } from "./components/bc-menu/bc-menu";
export { AutoPlayType, PerloadType } from "./components/bc-video/bc-video";
export namespace Components {
    interface BcBarrage {
    }
    interface BcMenu {
        "menuRender": () => Promise<any[]>;
        "menus": MenuItemType[];
    }
    interface BcVideo {
        "autoplay"?: AutoPlayType;
        "controls"?: boolean;
        "height"?: string | number;
        "loop"?: boolean;
        "muted"?: boolean;
        "poster"?: string;
        "preload"?: PerloadType;
        "src": string;
        "type"?: string;
        "width"?: string | number;
    }
}
declare global {
    interface HTMLBcBarrageElement extends Components.BcBarrage, HTMLStencilElement {
    }
    var HTMLBcBarrageElement: {
        prototype: HTMLBcBarrageElement;
        new (): HTMLBcBarrageElement;
    };
    interface HTMLBcMenuElement extends Components.BcMenu, HTMLStencilElement {
    }
    var HTMLBcMenuElement: {
        prototype: HTMLBcMenuElement;
        new (): HTMLBcMenuElement;
    };
    interface HTMLBcVideoElement extends Components.BcVideo, HTMLStencilElement {
    }
    var HTMLBcVideoElement: {
        prototype: HTMLBcVideoElement;
        new (): HTMLBcVideoElement;
    };
    interface HTMLElementTagNameMap {
        "bc-barrage": HTMLBcBarrageElement;
        "bc-menu": HTMLBcMenuElement;
        "bc-video": HTMLBcVideoElement;
    }
}
declare namespace LocalJSX {
    interface BcBarrage {
    }
    interface BcMenu {
        "menus"?: MenuItemType[];
    }
    interface BcVideo {
        "autoplay"?: AutoPlayType;
        "controls"?: boolean;
        "height"?: string | number;
        "loop"?: boolean;
        "muted"?: boolean;
        "poster"?: string;
        "preload"?: PerloadType;
        "src"?: string;
        "type"?: string;
        "width"?: string | number;
    }
    interface IntrinsicElements {
        "bc-barrage": BcBarrage;
        "bc-menu": BcMenu;
        "bc-video": BcVideo;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bc-barrage": LocalJSX.BcBarrage & JSXBase.HTMLAttributes<HTMLBcBarrageElement>;
            "bc-menu": LocalJSX.BcMenu & JSXBase.HTMLAttributes<HTMLBcMenuElement>;
            "bc-video": LocalJSX.BcVideo & JSXBase.HTMLAttributes<HTMLBcVideoElement>;
        }
    }
}
